[package]
name = "day04"
authors.workspace = true
description.workspace = true
version.workspace = true
edition.workspace = true

[dependencies]
aoc_libs.workspace = true
nom.workspace = true
collection_literals.workspace = true
